[build]
  publish = "public"
  command = """\
    curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
    tar -xf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
    rm dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
    export PATH=/opt/build/repo/dart-sass:$PATH && \
    hugo --gc --minify \
    """
    
[build.environment]
  HUGO_VERSION = "0.142.0"
  HUGO_ENV = "production"
  DART_SASS_VERSION = "1.83.4"
  HUGO_ENABLEGITINFO = "true"
  NODE_VERSION = "22"  # Ensure only one version is defined
  GO_VERSION = "1.23.5"
  TZ = "America/New_York"

[context.production.environment]
  HUGO_VERSION = "0.142.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.142.0"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.142.0"

[dev]
  command = "hugo server"
  port = 8888
  targetPort = 1313

[[redirects]]
  from = "/sitemap"
  to = "/sitemap.xml"
  status = 301
  force = true

# netlify.toml
[[headers]]
for = "/*"
  [headers.values]
  # Security headers
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "same-origin" # or "strict-origin-when-cross-origin"
  X-Permitted-Cross-Domain-Policies = "none"
  Permissions-Policy = "accelerometer=(self), autoplay=(self), camera=(self), encrypted-media=(self), fullscreen=(self), geolocation=(self), gyroscope=(self), magnetometer=(self), microphone=(self), midi=(self), payment=(self), publickey-credentials-get=(self), sync-xhr=(self), usb=(self), xr-spatial-tracking=(self)"

  Content-Security-Policy = """
    default-src 'none';
    script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.clarity.ms https://scripts.clarity.ms;
    script-src-elem 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.clarity.ms https://scripts.clarity.ms;
    style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
    img-src 'self' data: https://*.twic.pics https://*.googleusercontent.com https://maps.gstatic.com https://www.facebook.com https://*.facebook.com https://www.gstatic.com https://*.clarity.ms https://c.bing.com;
    font-src 'self' https://fonts.gstatic.com;
    media-src 'self';
    connect-src 'self' https://www.google-analytics.com https://region1.google-analytics.com https://stats.g.doubleclick.net https://www.googletagmanager.com https://www.google.com https://www.recaptcha.net https://www.facebook.com https://graph.facebook.com https://*.clarity.ms;
    object-src 'none';
    frame-src 'self' https://www.google.com https://www.recaptcha.net;
    form-action 'self';
    frame-ancestors 'none';
    manifest-src 'self';
    base-uri 'self';
  """

  # Content-Security-Policy-Report-Only = """
  #   default-src 'none';
  #   script-src 'self' https://www.googletagmanager.com https://www.clarity.ms https://scripts.clarity.ms;
  #   script-src-elem 'self' https://www.googletagmanager.com https://www.clarity.ms https://scripts.clarity.ms;
  #   style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
  #   img-src 'self' data: https://*.twic.pics https://*.googleusercontent.com https://maps.gstatic.com https://www.facebook.com https://*.facebook.com https://www.gstatic.com https://*.clarity.ms https://c.bing.com;
  #   font-src 'self' https://fonts.gstatic.com;
  #   media-src 'self';
  #   connect-src 'self' https://www.google-analytics.com https://region1.google-analytics.com https://stats.g.doubleclick.net https://www.googletagmanager.com https://www.google.com https://www.recaptcha.net https://www.facebook.com https://graph.facebook.com https://*.clarity.ms;
  #   object-src 'none';
  #   frame-src 'self' https://www.google.com https://www.recaptcha.net;
  #   form-action 'self';
  #   frame-ancestors 'none';
  #   manifest-src 'self';
  #   base-uri 'self';
  # """
